// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.shiki.proto;

public interface MyResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shiki.proto.MyResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.shiki.proto.MyRequestStream myRequestStream = 1;</code>
   */
  java.util.List<MyRequestStream> 
      getMyRequestStreamList();
  /**
   * <code>repeated .com.shiki.proto.MyRequestStream myRequestStream = 1;</code>
   */
  MyRequestStream getMyRequestStream(int index);
  /**
   * <code>repeated .com.shiki.proto.MyRequestStream myRequestStream = 1;</code>
   */
  int getMyRequestStreamCount();
  /**
   * <code>repeated .com.shiki.proto.MyRequestStream myRequestStream = 1;</code>
   */
  java.util.List<? extends MyRequestStreamOrBuilder> 
      getMyRequestStreamOrBuilderList();
  /**
   * <code>repeated .com.shiki.proto.MyRequestStream myRequestStream = 1;</code>
   */
  MyRequestStreamOrBuilder getMyRequestStreamOrBuilder(
          int index);
}
