// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.shiki.proto;

public interface MyRequestStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shiki.proto.MyRequestStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 age = 1;</code>
   */
  int getAge();
}
