// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.shiki.proto;

public interface MyResponseStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shiki.proto.MyResponseStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>optional string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>optional string city = 3;</code>
   */
  String getCity();
  /**
   * <code>optional string city = 3;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
