// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.shiki.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shiki.proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string realname = 2;</code>
   */
  String getRealname();
  /**
   * <code>optional string realname = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
