// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.shiki.proto;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiki_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiki_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiki_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiki_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiki_proto_MyRequestStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiki_proto_MyRequestStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiki_proto_MyResponseStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiki_proto_MyResponseStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiki_proto_MyResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiki_proto_MyResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Person.proto\022\017com.shiki.proto\"\035\n\tMyReq" +
      "uest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010" +
      "realname\030\002 \001(\t\"\036\n\017MyRequestStream\022\013\n\003age" +
      "\030\001 \001(\005\"?\n\020MyResponseStream\022\020\n\010username\030\001" +
      " \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"K\n\016MyRes" +
      "ponseList\0229\n\017myRequestStream\030\001 \003(\0132 .com" +
      ".shiki.proto.MyRequestStream2\227\002\n\rPersonS" +
      "ervice\022R\n\025GetRealNameByUsername\022\032.com.sh" +
      "iki.proto.MyRequest\032\033.com.shiki.proto.My" +
      "Response\"\000\022Z\n\017GetStudentByAge\022 .com.shik",
      "i.proto.MyRequestStream\032!.com.shiki.prot" +
      "o.MyResponseStream\"\0000\001\022V\n\023GetMyResponseS" +
      "tream\022\032.com.shiki.proto.MyRequest\032\037.com." +
      "shiki.proto.MyResponseList\"\000(\001B \n\017com.sh" +
      "iki.protoB\013PersonProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_shiki_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_shiki_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiki_proto_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_shiki_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_shiki_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiki_proto_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_shiki_proto_MyRequestStream_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_shiki_proto_MyRequestStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiki_proto_MyRequestStream_descriptor,
        new String[] { "Age", });
    internal_static_com_shiki_proto_MyResponseStream_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_shiki_proto_MyResponseStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiki_proto_MyResponseStream_descriptor,
        new String[] { "Username", "Age", "City", });
    internal_static_com_shiki_proto_MyResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_shiki_proto_MyResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiki_proto_MyResponseList_descriptor,
        new String[] { "MyRequestStream", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
